import Torre from "../assets/3torre_hero.jpg";
import Dusit from "../assets/dusit_residence_hero.jpg";
import SMDC from "../assets/for_buy.jpg";
import JAZZ from "../assets/for_rent.jpg";
import TownHouse from "../assets/for_sell.jpg";
import TwentyFour from "../assets/samujana-twenty-four.webp";
import AyalaResidence from "../assets/AyalaResidences.jpg";
import SegundaResidence from "../assets/SegundaResidence.jpg";
import Townhouse from "../assets/Townhouse.webp";
import Alder from "../assets/AlderRes.webp";
import AyalaWest from "../assets/Ayala-West.jpg";
import CommonWealth from "../assets/CommonwealthRes.jpg";
import Mango from "../assets/MangoCondo.jpg";
import SienaTownhouse from "../assets/SienaTownhouse.webp";
import SienaBungalow from "../assets/SienaBungalow.webp";


export const allProperties = [
  {
    name: "MAKATI CONDOMINIUM",
    image: Torre,
    price: 19999999.99,
    region: "Luzon",
    city: "Metro Manila",
    locality: ["Luzon", "Metro Manila"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 1,
  },
  {
    name: "DUSIT RESIDENCES",
    image: Dusit,
    price: 29999999.99,
    region: "Luzon",
    city: "Metro Manila",
    locality:["Luzon", "Metro Manila"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 2
  },
  {
    name: "PRIME RESIDENCES",
    region: "Luzon",
    city: "Metro Manila",
    locality:[],
    image: SMDC,
    price: 11999999.99,
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 3,
  },
  {
    name: "SM JAZZ",
    image: JAZZ,
    price: 15999999.99,
    region: "Luzon",
    city: "",
    locality: "Luzon",
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 4,
  },
  {
    name: "TOWN HOUSE",
    image: TownHouse,
    price: 6999999.99,
    region: "Luzon",
    city: "",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 5,
  },
  {
    name: "SAMUJANA TWENTY FOUR",
    image: TwentyFour,
    price: 9999999.99,
    region: "Visayas",
    city: "Cebu",
    locality:["Visayas", "Cebu"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 6,
  },
  {
    name: "SAN JUAN RESIDENCES",
    image: TwentyFour,
    price: 9999999.99,
    region: "Visayas",
    city: "Cebu",
    locality:["Visayas", "Cebu"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 7,
  },
  {
    name: "ORTIGAS RESIDENCES",
    image: TownHouse,
    price: 9999999.99,
    region: "Visayas",
    city: "",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 8,
  },
  {
    name: "AYALA RESIDENCES",
    image: AyalaResidence,
    price: 9999999.99,
    region: "Visayas",
    city: "",
    locality:["Visayas"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 9,
  },
  {
    name: "SEGUNDA RESIDENCES",
    image: SegundaResidence,
    price: 14999999.99,
    region: "Visayas",
    city: "Cebu",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 10,
  },
  {
    name: "LUMINA TOWNHOUSE",
    image: Townhouse,
    price: 8999999.99,
    region: "Mindanao",
    city: "Davao",
    locality:["Mindanao","Davao"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 11,
  },
  {
    name: "ALDER RESIDENCES",
    image: Alder,
    price: 23999999.99,
    region: "Mindanao",
    city: "Davao",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 12,
  },
  {
    name: "AYALA WEST",
    image: AyalaWest,
    price: 21999999.99,
    region: "Mindanao",
    city: "Davao",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 13,
  },
  {
    name: "COMMONWEALTH RESIDENCES",
    image: CommonWealth,
    price: 26999999.99,
    region: "Mindanao",
    city: "",
    locality:["Mindanao"],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 14,
  },
  {
    name: "MANGO CONDO",
    image: Mango,
    price: 7999999.99,
    region: "Mindanao",
    city: "",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 15,
  },
  {
    name: "SIENA TOWNHOUSE",
    image: SienaTownhouse,
    price: 17999999.99,
    region: "Mindanao",
    city: "",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 16,
  },
  {
    name: "SIENA BUNGALOW",
    image: SienaBungalow,
    price: 21999999.99,
    region: "Visayas",
    city: "Cebu",
    locality:[],
    floorarea: "300 SQM",
    lotarea: "",
    description: "Located in the heart of Makati, this condo is fully furnished and ready for occupancy. <br/> Five Bedrooms + Four Toilet & Baths + Kitchen + Dining + Living Area + Balcony.",
    id: 17,
  },
];
